### ISSUE TITLE
Nákvæmur skiladagur

### ISSUE THREAD

**Issue by Culmenus** [vefforritun/vef1-2020-v5#1]
Það er óljóst hvenær nákvæmlega skil verða "sein".
Það virðist vera út frá samhengi við 23:59 6. okt m.t.t. 10% slegin af hámarkseinkunn sem verður max 30% á föstudaginn.
Geturðu staðfest hvenær skil verða sein?

**Comment by osk** [comment]
Skil verða sein ef þeim er skilað eftir skiladag sem er 6. okt fram til 23:59, þ.e.a.s. kl. 00:00 eða seinna 7. okt.
Þá er dregið niður um 10% eftir hvern sólarhing:

* -10% ef skilað milli 00:00-23:59 7. okt
* -20% ef skilað milli 00:00-23:59 8. okt
* -30% ef skilað milli 00:00-23:59 9. okt

Kl. 00:00 10. okt er lokað fyrir skil.

Nógu skýrt, @Culmenus ?
